### ISSUE TITLE
How to know result IRI is literal or named node?

### ISSUE THREAD

**Issue by pheyvaer** [rubensworks/GraphQL-LD.js#40]
Using the following context and output from the README, how do you if the value of `starring` in the original data that was queried is a literal or a named node?

```json
{
  "@context": {
    "Film": "http://dbpedia.org/ontology/Film",
    "label": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
    "starring": "http://dbpedia.org/ontology/starring"
  }
}
```

```json
{
  "data": [
    {
      "id": "http://dbpedia.org/resource/Ocean's_Eleven",
      "starring": "http://dbpedia.org/resource/Brad_Pitt"
    },
    {
      "id": "http://dbpedia.org/resource/The_Favor",
      "starring": "http://dbpedia.org/resource/Brad_Pitt"
    },
    {
      "id": "http://dbpedia.org/resource/The_Assassination_of_Jesse_James_by_the_Coward_Robert_Ford",
      "starring": "http://dbpedia.org/resource/Brad_Pitt"
    },
    {
      "id": "http://dbpedia.org/resource/True_Romance",
      "starring": "http://dbpedia.org/resource/Brad_Pitt"
    },
    ...
  ]
}
```

**Comment by rubensworks** [comment]
It's been a while since I worked on this, but it looks like this tool is hardcoded to [materialize RDF/JS terms to strings](https://github.com/rubensworks/GraphQL-LD.js/blob/master/lib/Client.ts#L34), so there's no way of distinguishing literals vs IRIs in that case.

You can however pass your own `SparqlJsonToTreeConverter` into the constructor: https://github.com/rubensworks/GraphQL-LD.js/blob/master/lib/Client.ts#L119
This allows you to set `materializeRdfJsTerms` to false: https://github.com/rubensworks/sparqljson-to-tree.js#create-a-new-converter

**Comment by pheyvaer** [comment]
Cool! I will have a look at doing it that way. Thanks!

**Comment by pheyvaer** [comment]
It worked 🎉
